#!/usr/bin/env bash

# Don't allow commiting on the main branch
branch_name= git rev-parse --abbrev-ref HEAD
if [ "$branch_name" = "main" ]; then
  echo "You shouldn't commit directly to main!!!"
  echo "You can create a new branch using: git checkout -b my-branch-name"
  exit 1
fi

# TODO: Check proper formatting
