package tui

import "github.com/charmbracelet/bubbles/list"

var (
	StocksList = []list.Item{
		stock{
			title:       "AAPL",
			description: "Apple stock",
			sellPrices:  []int32{100, 120, 130, 140, 1000, 10001, 100, 200, 30, 300},
			sellAmount:  []uint32{100, 120, 130, 140, 1000, 10001, 100, 200, 30, 300},
			buyPrices:   []int32{100, 120, 130, 140, 1000, 10001, 100, 200, 30, 300},
			buyAmount:   []uint32{100, 120, 130, 140, 1000, 10001, 100, 200, 30, 300},
		},
		stock{
			title:       "AMZN",
			description: "Amazon stock",
			sellPrices:  []int32{130, 140, 1000, 10001, 100, 200, 30, 300},
			sellAmount:  []uint32{130, 140, 1000, 10001, 100, 200, 30, 300},
			buyPrices:   []int32{130, 140, 1000, 10001, 100, 200, 30, 300},
			buyAmount:   []uint32{130, 140, 1000, 10001, 100, 200, 30, 300},
		},
		stock{
			title:       "MSFT",
			description: "Microsoft stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "GOOG",
			description: "Alphabet Inc. stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "NFLX",
			description: "Netflix stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "TSLA",
			description: "Tesla stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "FB",
			description: "Meta stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "TSM",
			description: "Taiwan Semiconductor Manufacturing stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "NVDA",
			description: "NVIDIA stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "V",
			description: "Visa stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "WMT",
			description: "Walmart stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "JPM",
			description: "JP Morgan stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "MA",
			description: "Mastercard stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "PEP",
			description: "PepsiCo  stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "DIS",
			description: "Walt Disney stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "CSCO",
			description: "Cisco Systems stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "VZ",
			description: "Verizon stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "ORCL",
			description: "Oracle Corporation stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "NKE",
			description: "Nike stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "ADBE",
			description: "Adobe stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
		stock{
			title:       "INTC",
			description: "Intel Corporation stock",
			sellPrices:  []int32{},
			sellAmount:  []uint32{},
			buyPrices:   []int32{},
			buyAmount:   []uint32{},
		},
	}

	StocksArray = []stock{
		stock{title: "AAPL", description: "Apple stock", stockId: 1, sellSide: []order{order{price: 100}, order{price: 101}, order{price: 99}, order{price: 104}}},
		stock{title: "AMZN", description: "Amazon stock", stockId: 2},
		stock{title: "MSFT", description: "Microsoft stock", stockId: 3},
		stock{title: "GOOG", description: "Alphabet Inc. stock", stockId: 4},
		stock{title: "NFLX", description: "Netflix stock", stockId: 5},
		stock{title: "TSLA", description: "Tesla stock", stockId: 6},
		stock{title: "FB", description: "Meta stock", stockId: 7},
		stock{title: "TSM", description: "Taiwan Semiconductor Manufacturing stock", stockId: 8},
		stock{title: "NVDA", description: "NVIDIA stock", stockId: 9},
		stock{title: "V", description: "Visa stock", stockId: 10},
		stock{title: "WMT", description: "Walmart stock", stockId: 11},
		stock{title: "JPM", description: "JP Morgan stock", stockId: 12},
		stock{title: "MA", description: "Mastercard stock", stockId: 13},
		stock{title: "PEP", description: "PepsiCo  stock", stockId: 14},
		stock{title: "DIS", description: "Walt Disney stock", stockId: 15},
		stock{title: "CSCO", description: "Cisco Systems stock", stockId: 16},
		stock{title: "VZ", description: "Verizon stock", stockId: 17},
		stock{title: "ORCL", description: "Oracle Corporation stock", stockId: 18},
		stock{title: "NKE", description: "Nike stock", stockId: 19},
		stock{title: "ADBE", description: "Adobe stock", stockId: 20},
		stock{title: "INTC", description: "Intel Corporation stock", stockId: 21},
	}
)
