// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: matching-engine/matchingEngine.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecurityOrder_OrderSide int32

const (
	SecurityOrder_Buy  SecurityOrder_OrderSide = 0
	SecurityOrder_Sell SecurityOrder_OrderSide = 1
)

// Enum value maps for SecurityOrder_OrderSide.
var (
	SecurityOrder_OrderSide_name = map[int32]string{
		0: "Buy",
		1: "Sell",
	}
	SecurityOrder_OrderSide_value = map[string]int32{
		"Buy":  0,
		"Sell": 1,
	}
)

func (x SecurityOrder_OrderSide) Enum() *SecurityOrder_OrderSide {
	p := new(SecurityOrder_OrderSide)
	*p = x
	return p
}

func (x SecurityOrder_OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityOrder_OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_matching_engine_matchingEngine_proto_enumTypes[0].Descriptor()
}

func (SecurityOrder_OrderSide) Type() protoreflect.EnumType {
	return &file_matching_engine_matchingEngine_proto_enumTypes[0]
}

func (x SecurityOrder_OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityOrder_OrderSide.Descriptor instead.
func (SecurityOrder_OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_matching_engine_matchingEngine_proto_rawDescGZIP(), []int{0, 0}
}

type CreateOrderRequest_OrderType int32

const (
	CreateOrderRequest_Limit  CreateOrderRequest_OrderType = 0 // TODO: check if this is correct
	CreateOrderRequest_Market CreateOrderRequest_OrderType = 1
)

// Enum value maps for CreateOrderRequest_OrderType.
var (
	CreateOrderRequest_OrderType_name = map[int32]string{
		0: "Limit",
		1: "Market",
	}
	CreateOrderRequest_OrderType_value = map[string]int32{
		"Limit":  0,
		"Market": 1,
	}
)

func (x CreateOrderRequest_OrderType) Enum() *CreateOrderRequest_OrderType {
	p := new(CreateOrderRequest_OrderType)
	*p = x
	return p
}

func (x CreateOrderRequest_OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateOrderRequest_OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_matching_engine_matchingEngine_proto_enumTypes[1].Descriptor()
}

func (CreateOrderRequest_OrderType) Type() protoreflect.EnumType {
	return &file_matching_engine_matchingEngine_proto_enumTypes[1]
}

func (x CreateOrderRequest_OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateOrderRequest_OrderType.Descriptor instead.
func (CreateOrderRequest_OrderType) EnumDescriptor() ([]byte, []int) {
	return file_matching_engine_matchingEngine_proto_rawDescGZIP(), []int{1, 0}
}

type SecurityOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price         int32                   `protobuf:"zigzag32,1,opt,name=price,proto3" json:"price,omitempty"`
	SecurityId    uint32                  `protobuf:"varint,2,opt,name=securityId,proto3" json:"securityId,omitempty"`
	OrderQuantity uint32                  `protobuf:"varint,3,opt,name=orderQuantity,proto3" json:"orderQuantity,omitempty"`
	OrderSide     SecurityOrder_OrderSide `protobuf:"varint,4,opt,name=orderSide,proto3,enum=matching_engine.SecurityOrder_OrderSide" json:"orderSide,omitempty"`
}

func (x *SecurityOrder) Reset() {
	*x = SecurityOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matching_engine_matchingEngine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityOrder) ProtoMessage() {}

func (x *SecurityOrder) ProtoReflect() protoreflect.Message {
	mi := &file_matching_engine_matchingEngine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityOrder.ProtoReflect.Descriptor instead.
func (*SecurityOrder) Descriptor() ([]byte, []int) {
	return file_matching_engine_matchingEngine_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityOrder) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SecurityOrder) GetSecurityId() uint32 {
	if x != nil {
		return x.SecurityId
	}
	return 0
}

func (x *SecurityOrder) GetOrderQuantity() uint32 {
	if x != nil {
		return x.OrderQuantity
	}
	return 0
}

func (x *SecurityOrder) GetOrderSide() SecurityOrder_OrderSide {
	if x != nil {
		return x.OrderSide
	}
	return SecurityOrder_Buy
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecurityOrder *SecurityOrder               `protobuf:"bytes,1,opt,name=securityOrder,proto3" json:"securityOrder,omitempty"`
	OrderId       uint64                       `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	OrderType     CreateOrderRequest_OrderType `protobuf:"varint,3,opt,name=orderType,proto3,enum=matching_engine.CreateOrderRequest_OrderType" json:"orderType,omitempty"`
	SenderId      []byte                       `protobuf:"bytes,4,opt,name=senderId,proto3" json:"senderId,omitempty"`
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matching_engine_matchingEngine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_engine_matchingEngine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_matching_engine_matchingEngine_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetSecurityOrder() *SecurityOrder {
	if x != nil {
		return x.SecurityOrder
	}
	return nil
}

func (x *CreateOrderRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateOrderRequest) GetOrderType() CreateOrderRequest_OrderType {
	if x != nil {
		return x.OrderType
	}
	return CreateOrderRequest_Limit
}

func (x *CreateOrderRequest) GetSenderId() []byte {
	if x != nil {
		return x.SenderId
	}
	return nil
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matching_engine_matchingEngine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_engine_matchingEngine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_matching_engine_matchingEngine_proto_rawDescGZIP(), []int{2}
}

// in the future the client should probably specify a list of securityIds it's interested in following
type PublishTradeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishTradeRequest) Reset() {
	*x = PublishTradeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matching_engine_matchingEngine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTradeRequest) ProtoMessage() {}

func (x *PublishTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_engine_matchingEngine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTradeRequest.ProtoReflect.Descriptor instead.
func (*PublishTradeRequest) Descriptor() ([]byte, []int) {
	return file_matching_engine_matchingEngine_proto_rawDescGZIP(), []int{3}
}

type PublishTradeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecurityOrder *SecurityOrder `protobuf:"bytes,1,opt,name=securityOrder,proto3" json:"securityOrder,omitempty"`
}

func (x *PublishTradeResponse) Reset() {
	*x = PublishTradeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matching_engine_matchingEngine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishTradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTradeResponse) ProtoMessage() {}

func (x *PublishTradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_engine_matchingEngine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTradeResponse.ProtoReflect.Descriptor instead.
func (*PublishTradeResponse) Descriptor() ([]byte, []int) {
	return file_matching_engine_matchingEngine_proto_rawDescGZIP(), []int{4}
}

func (x *PublishTradeResponse) GetSecurityOrder() *SecurityOrder {
	if x != nil {
		return x.SecurityOrder
	}
	return nil
}

type PublishOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishOrderRequest) Reset() {
	*x = PublishOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matching_engine_matchingEngine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishOrderRequest) ProtoMessage() {}

func (x *PublishOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_engine_matchingEngine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishOrderRequest.ProtoReflect.Descriptor instead.
func (*PublishOrderRequest) Descriptor() ([]byte, []int) {
	return file_matching_engine_matchingEngine_proto_rawDescGZIP(), []int{5}
}

type PublishOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecurityOrder *SecurityOrder `protobuf:"bytes,1,opt,name=securityOrder,proto3" json:"securityOrder,omitempty"`
}

func (x *PublishOrderResponse) Reset() {
	*x = PublishOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matching_engine_matchingEngine_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishOrderResponse) ProtoMessage() {}

func (x *PublishOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_engine_matchingEngine_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishOrderResponse.ProtoReflect.Descriptor instead.
func (*PublishOrderResponse) Descriptor() ([]byte, []int) {
	return file_matching_engine_matchingEngine_proto_rawDescGZIP(), []int{6}
}

func (x *PublishOrderResponse) GetSecurityOrder() *SecurityOrder {
	if x != nil {
		return x.SecurityOrder
	}
	return nil
}

var File_matching_engine_matchingEngine_proto protoreflect.FileDescriptor

var file_matching_engine_matchingEngine_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67,
	0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x22, 0xd3, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x0d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x51, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x46, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x69,
	0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x69,
	0x64, 0x65, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x69, 0x64, 0x65, 0x22, 0x1e, 0x0a,
	0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x69, 0x64, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x75,
	0x79, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x65, 0x6c, 0x6c, 0x10, 0x01, 0x22, 0x81, 0x02,
	0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x44, 0x0a, 0x0d, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x53, 0x65,
	0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x0d, 0x73, 0x65, 0x63,
	0x75, 0x72, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x4b, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69,
	0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x22, 0x0a,
	0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x10,
	0x01, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x5c, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0d, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x0d,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x15, 0x0a,
	0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0d,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x0d, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x32, 0xb6, 0x02, 0x0a, 0x0e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x45,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x5a, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x5f, 0x0a, 0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x72, 0x61, 0x64,
	0x65, 0x12, 0x24, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69,
	0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x67, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x74, 0x66, 0x2d, 0x70,
	0x70, 0x2f, 0x32, 0x30, 0x32, 0x32, 0x5f, 0x4d, 0x41, 0x54, 0x44, 0x41, 0x51, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_matching_engine_matchingEngine_proto_rawDescOnce sync.Once
	file_matching_engine_matchingEngine_proto_rawDescData = file_matching_engine_matchingEngine_proto_rawDesc
)

func file_matching_engine_matchingEngine_proto_rawDescGZIP() []byte {
	file_matching_engine_matchingEngine_proto_rawDescOnce.Do(func() {
		file_matching_engine_matchingEngine_proto_rawDescData = protoimpl.X.CompressGZIP(file_matching_engine_matchingEngine_proto_rawDescData)
	})
	return file_matching_engine_matchingEngine_proto_rawDescData
}

var file_matching_engine_matchingEngine_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_matching_engine_matchingEngine_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_matching_engine_matchingEngine_proto_goTypes = []interface{}{
	(SecurityOrder_OrderSide)(0),      // 0: matching_engine.SecurityOrder.OrderSide
	(CreateOrderRequest_OrderType)(0), // 1: matching_engine.CreateOrderRequest.OrderType
	(*SecurityOrder)(nil),             // 2: matching_engine.SecurityOrder
	(*CreateOrderRequest)(nil),        // 3: matching_engine.CreateOrderRequest
	(*CreateOrderResponse)(nil),       // 4: matching_engine.CreateOrderResponse
	(*PublishTradeRequest)(nil),       // 5: matching_engine.PublishTradeRequest
	(*PublishTradeResponse)(nil),      // 6: matching_engine.PublishTradeResponse
	(*PublishOrderRequest)(nil),       // 7: matching_engine.PublishOrderRequest
	(*PublishOrderResponse)(nil),      // 8: matching_engine.PublishOrderResponse
}
var file_matching_engine_matchingEngine_proto_depIdxs = []int32{
	0, // 0: matching_engine.SecurityOrder.orderSide:type_name -> matching_engine.SecurityOrder.OrderSide
	2, // 1: matching_engine.CreateOrderRequest.securityOrder:type_name -> matching_engine.SecurityOrder
	1, // 2: matching_engine.CreateOrderRequest.orderType:type_name -> matching_engine.CreateOrderRequest.OrderType
	2, // 3: matching_engine.PublishTradeResponse.securityOrder:type_name -> matching_engine.SecurityOrder
	2, // 4: matching_engine.PublishOrderResponse.securityOrder:type_name -> matching_engine.SecurityOrder
	3, // 5: matching_engine.MatchingEngine.CreateOrder:input_type -> matching_engine.CreateOrderRequest
	5, // 6: matching_engine.MatchingEngine.PublishTrade:input_type -> matching_engine.PublishTradeRequest
	7, // 7: matching_engine.MatchingEngine.PublishOrderCreation:input_type -> matching_engine.PublishOrderRequest
	4, // 8: matching_engine.MatchingEngine.CreateOrder:output_type -> matching_engine.CreateOrderResponse
	6, // 9: matching_engine.MatchingEngine.PublishTrade:output_type -> matching_engine.PublishTradeResponse
	8, // 10: matching_engine.MatchingEngine.PublishOrderCreation:output_type -> matching_engine.PublishOrderResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_matching_engine_matchingEngine_proto_init() }
func file_matching_engine_matchingEngine_proto_init() {
	if File_matching_engine_matchingEngine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_matching_engine_matchingEngine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matching_engine_matchingEngine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matching_engine_matchingEngine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matching_engine_matchingEngine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishTradeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matching_engine_matchingEngine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishTradeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matching_engine_matchingEngine_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matching_engine_matchingEngine_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_matching_engine_matchingEngine_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matching_engine_matchingEngine_proto_goTypes,
		DependencyIndexes: file_matching_engine_matchingEngine_proto_depIdxs,
		EnumInfos:         file_matching_engine_matchingEngine_proto_enumTypes,
		MessageInfos:      file_matching_engine_matchingEngine_proto_msgTypes,
	}.Build()
	File_matching_engine_matchingEngine_proto = out.File
	file_matching_engine_matchingEngine_proto_rawDesc = nil
	file_matching_engine_matchingEngine_proto_goTypes = nil
	file_matching_engine_matchingEngine_proto_depIdxs = nil
}
