name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build client
      run: |
        cd client
        make

    - name: Build user-service
      run: |
        cd user-service
        make
    
    - name: Formatting
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
